# Generated by Django 5.1.5 on 2025-01-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='cannot_follow_self',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
